"use client";

import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Download,
  Share2,
  Copy,
  FileText,
  Rocket,
  ExternalLink,
  CheckCircle
} from 'lucide-react';
import {
  OrbitalElements,
  OrbitalCharacteristics
} from '@/lib/orbital-mechanics';
import {
  exportMissionData,
  LearningLevel
} from '@/lib/education-utils';

interface MissionExportProps {
  elements: OrbitalElements;
  characteristics: OrbitalCharacteristics;
  learningLevel: LearningLevel;
  onClose?: () => void;
}

export default function MissionExport({
  elements,
  characteristics,
  learningLevel,
  onClose
}: MissionExportProps) {
  const [copied, setCopied] = useState<string | null>(null);

  const handleExport = (format: 'gmat' | 'stk' | 'json') => {
    try {
      const exportResult = exportMissionData(elements, format);

      // Create and download file
      const blob = new Blob([exportResult.data], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = exportResult.filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Export failed:', error);
    }
  };

  const handleShareURL = async () => {
    const urlParams = new URLSearchParams({
      sma: elements.semiMajorAxis.toString(),
      ecc: elements.eccentricity.toString(),
      inc: elements.inclination.toString(),
      raan: elements.raan.toString(),
      aop: elements.argumentOfPeriapsis.toString(),
      ta: elements.trueAnomaly.toString()
    });

    const shareURL = `${window.location.origin}${window.location.pathname}?${urlParams.toString()}`;

    try {
      await navigator.clipboard.writeText(shareURL);
      setCopied('url');
      setTimeout(() => setCopied(null), 2000);
    } catch (error) {
      console.error('Failed to copy URL:', error);
    }
  };

  const handleCopyData = async (format: 'gmat' | 'stk' | 'json') => {
    try {
      const exportResult = exportMissionData(elements, format);
      await navigator.clipboard.writeText(exportResult.data);
      setCopied(format);
      setTimeout(() => setCopied(null), 2000);
    } catch (error) {
      console.error('Copy failed:', error);
    }
  };

  const generateSummary = () => {
    return `Mission Summary:
• Altitude: ${characteristics.altitude.toFixed(0)} km
• Orbital Period: ${characteristics.period.toFixed(1)} minutes
• Inclination: ${characteristics.inclination.toFixed(1)}°
• Eccentricity: ${characteristics.eccentricity.toFixed(4)}
• Apogee: ${characteristics.apogee.toFixed(0)} km
• Perigee: ${characteristics.perigee.toFixed(0)} km
• Velocity: ${characteristics.velocity.toFixed(2)} km/s

Generated by Astrodynamics Playground
Learning Level: ${learningLevel.charAt(0).toUpperCase() + learningLevel.slice(1)}`;
  };

  return (
    <Card className="w-full max-w-sm bg-background shadow-lg border">
      <CardHeader className="pb-3">
        <CardTitle className="text-lg flex items-center gap-2">
          <Rocket className="h-5 w-5" />
          Mission Export
        </CardTitle>
        <p className="text-sm text-muted-foreground">
          Export your orbital mission for professional tools or sharing
        </p>
      </CardHeader>

      <CardContent>
        <Tabs defaultValue="share" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="share" className="text-xs">Share</TabsTrigger>
            <TabsTrigger value="professional" className="text-xs">Professional</TabsTrigger>
            <TabsTrigger value="summary" className="text-xs">Summary</TabsTrigger>
          </TabsList>

          {/* Share Tab */}
          <TabsContent value="share" className="space-y-3 mt-4">
            <div>
              <h4 className="font-medium mb-2 flex items-center gap-1">
                <Share2 className="h-4 w-4" />
                Share Mission
              </h4>
              <p className="text-xs text-muted-foreground mb-3">
                Share your orbital parameters with others via URL
              </p>
              <Button
                onClick={handleShareURL}
                variant="outline"
                className="w-full justify-start"
                size="sm"
              >
                {copied === 'url' ? (
                  <CheckCircle className="h-4 w-4 mr-2 text-green-500" />
                ) : (
                  <Copy className="h-4 w-4 mr-2" />
                )}
                {copied === 'url' ? 'Copied to Clipboard!' : 'Copy Shareable URL'}
              </Button>
            </div>

            <div>
              <h4 className="font-medium mb-2">Quick Data Export</h4>
              <Button
                onClick={() => handleCopyData('json')}
                variant="outline"
                className="w-full justify-start"
                size="sm"
              >
                {copied === 'json' ? (
                  <CheckCircle className="h-4 w-4 mr-2 text-green-500" />
                ) : (
                  <FileText className="h-4 w-4 mr-2" />
                )}
                {copied === 'json' ? 'Copied JSON Data!' : 'Copy as JSON'}
              </Button>
            </div>
          </TabsContent>

          {/* Professional Tools Tab */}
          <TabsContent value="professional" className="space-y-3 mt-4">
            <div>
              <h4 className="font-medium mb-2">Professional Software</h4>
              <p className="text-xs text-muted-foreground mb-3">
                Export for use in industry-standard mission design tools
              </p>
            </div>

            <div className="space-y-2">
              <div className="flex items-center justify-between p-3 border rounded-lg">
                <div>
                  <div className="font-medium text-sm">GMAT Script</div>
                  <div className="text-xs text-muted-foreground">
                    NASA's General Mission Analysis Tool
                  </div>
                </div>
                <div className="flex gap-1">
                  <Button
                    onClick={() => handleCopyData('gmat')}
                    variant="ghost"
                    size="sm"
                    className="h-8 w-8 p-0"
                  >
                    {copied === 'gmat' ? (
                      <CheckCircle className="h-3 w-3 text-green-500" />
                    ) : (
                      <Copy className="h-3 w-3" />
                    )}
                  </Button>
                  <Button
                    onClick={() => handleExport('gmat')}
                    variant="ghost"
                    size="sm"
                    className="h-8 w-8 p-0"
                  >
                    <Download className="h-3 w-3" />
                  </Button>
                </div>
              </div>

              <div className="flex items-center justify-between p-3 border rounded-lg">
                <div>
                  <div className="font-medium text-sm">STK Scenario</div>
                  <div className="text-xs text-muted-foreground">
                    AGI Systems Tool Kit
                  </div>
                </div>
                <div className="flex gap-1">
                  <Button
                    onClick={() => handleCopyData('stk')}
                    variant="ghost"
                    size="sm"
                    className="h-8 w-8 p-0"
                  >
                    {copied === 'stk' ? (
                      <CheckCircle className="h-3 w-3 text-green-500" />
                    ) : (
                      <Copy className="h-3 w-3" />
                    )}
                  </Button>
                  <Button
                    onClick={() => handleExport('stk')}
                    variant="ghost"
                    size="sm"
                    className="h-8 w-8 p-0"
                  >
                    <Download className="h-3 w-3" />
                  </Button>
                </div>
              </div>
            </div>

            {learningLevel === LearningLevel.BEGINNER && (
              <div className="p-3 bg-muted rounded-lg">
                <div className="text-xs text-muted-foreground">
                  💡 <strong>Learning Note:</strong> These formats are used by aerospace engineers for real mission planning and analysis.
                </div>
              </div>
            )}
          </TabsContent>

          {/* Summary Tab */}
          <TabsContent value="summary" className="space-y-3 mt-4">
            <div>
              <h4 className="font-medium mb-2">Mission Summary</h4>
              <div className="text-xs bg-muted p-3 rounded-lg font-mono whitespace-pre-line">
                {generateSummary()}
              </div>
            </div>

            <div className="flex gap-2">
              <Button
                onClick={async () => {
                  try {
                    await navigator.clipboard.writeText(generateSummary());
                    setCopied('summary');
                    setTimeout(() => setCopied(null), 2000);
                  } catch (error) {
                    console.error('Copy failed:', error);
                  }
                }}
                variant="outline"
                size="sm"
                className="flex-1"
              >
                {copied === 'summary' ? (
                  <CheckCircle className="h-3 w-3 mr-1 text-green-500" />
                ) : (
                  <Copy className="h-3 w-3 mr-1" />
                )}
                {copied === 'summary' ? 'Copied!' : 'Copy'}
              </Button>
              <Button
                onClick={() => {
                  const blob = new Blob([generateSummary()], { type: 'text/plain' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = `mission_summary_${Date.now()}.txt`;
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
                  URL.revokeObjectURL(url);
                }}
                variant="outline"
                size="sm"
                className="flex-1"
              >
                <Download className="h-3 w-3 mr-1" />
                Save
              </Button>
            </div>
          </TabsContent>
        </Tabs>

        {/* Professional Learning Links */}
        {learningLevel !== LearningLevel.BEGINNER && (
          <div className="mt-4 pt-3 border-t">
            <h5 className="text-xs font-medium mb-2">Learn More</h5>
            <div className="flex gap-2">
              <Button
                variant="ghost"
                size="sm"
                className="text-xs h-7"
                asChild
              >
                <a
                  href="https://gmatcentral.org/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1"
                >
                  GMAT
                  <ExternalLink className="h-3 w-3" />
                </a>
              </Button>
              <Button
                variant="ghost"
                size="sm"
                className="text-xs h-7"
                asChild
              >
                <a
                  href="https://www.agi.com/products/stk"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1"
                >
                  STK
                  <ExternalLink className="h-3 w-3" />
                </a>
              </Button>
            </div>
          </div>
        )}

        {onClose && (
          <div className="mt-4 pt-3 border-t">
            <Button
              onClick={onClose}
              variant="outline"
              size="sm"
              className="w-full"
            >
              Close
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}